### ISSUE TITLE
problem with docker machine creation

### ISSUE THREAD

**Issue by Cricen** [redhatdemocentral/ocp-install-demo#37] opened 2017-10-26 23:10 UTC
got the following error
docker version:  17.09.0-ce
OC version: 3.6.173
Virtual box version: 5.2.0
Centos 7
got the following error
docker version:  17.09.0-ce
OC version: 3.6.173
Virtual box version: 5.2.0
Centos 7

> OpenShift command line tools installed... checking for valid version...
Version of installed OpenShift command line tools correct... v3.6.173
Setting up OpenShift docker machine...
./init.sh: line 161: docker-machine: command not found
Error occurred during openshift docker machine creation...
Cleaning out existing 'openshift' machine...
./init.sh: line 169: docker-machine: command not found
Setting up new OpenShift docker machine...
./init.sh: line 173: docker-machine: command not found
Problem with docker machine creation that I can't resolve, please raise an issue and add error output:
>

**Comment by Cricen** [comment] 2017-10-27 03:35
Gave up on linux for the time being and got the same error on windows. To try and resolve it I tried to install docker-machine manually this time with git-bash. No dice. 
virtual box: 5.2.0
docker-machine version 0.12.2, build 9371605
docker 17.09.0-ce, build afdb6d4
windows 10 v1607
oc v3.6.173.0.49
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

got some different output after the docker-machine install 

>Version of installed OpenShift command line tools correct... v3.6.173.0.49
Setting up OpenShift docker machine...
Incorrect Usage.
Usage: docker-machine create [OPTIONS] [arg...]
Create a machine
Description:
   Run 'docker-machine create --driver name' to include the create flags for that driver in the help text.
Options:
-- I cut out the usage -- 
invalid value "" for flag -virtualbox-memory: strconv.ParseInt: parsing "": invalid syntax
Problem with docker machine creation that I can't resolve, please raise an issue and add error output:
   https://github.com/redhatdemocentral/ocp-install-demo/issues/new
>

**Comment by eschabell** [comment] 2017-10-27 08:45
@Cricen, the docker-machine for linux can be pulled from here: 

$ curl -L https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
chmod +x /tmp/docker-machine && sudo cp /tmp/docker-machine /usr/local/bin/docker-machine

Not sure how that works for Windows.

**Comment by Cricen** [comment] 2017-10-27 21:44
Think there was a typo in the curl command. I ran: 
```
curl -L https://github.com/docker/machine/releases/download/v0.12.2/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine &&
    chmod +x /tmp/docker-machine &&
    sudo cp /tmp/docker-machine /usr/local/bin/docker-machine
```
which works but still no dice but got a slightly different error which is good...

>OpenShift command line tools installed... checking for valid version...
Version of installed OpenShift command line tools correct... v3.6.173
Setting up OpenShift docker machine...
Driver "kvm" not found. Do you have the plugin binary "docker-machine-driver-kvm" accessible in your PATH?
Error occurred during openshift docker machine creation...
Cleaning out existing 'openshift' machine...
About to remove openshift
WARNING: This action will delete both local reference and remote instance.
Error removing host "openshift": Host does not exist: "openshift"
Can't remove "openshift"
Setting up new OpenShift docker machine...
Driver "kvm" not found. Do you have the plugin binary "docker-machine-driver-kvm" accessible in your PATH?
Problem with docker machine creation that I can't resolve, please raise an issue and add error output:
   https://github.com/redhatdemocentral/ocp-install-demo/issues/new
>

On windows to install docker machine manually I used git bash: 
```
if [[ ! -d "$HOME/bin" ]]; then mkdir -p "$HOME/bin"; fi && \
curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-Windows-x86_64.exe > "$HOME/bin/docker-machine.exe" && \
chmod +x "$HOME/bin/docker-machine.exe"
```

**Comment by Cricen** [comment] 2017-10-27 23:23
duh, my bad I overlooked the top where it says I would need docker-machine and docker-machine-driver-kvm. installed both and added them but now I'm getting: 


> Setting up OpenShift docker machine...
> dial tcp: missing address
> Error occurred during openshift docker machine creation...
> Cleaning out existing 'openshift' machine...
> About to remove openshift
> WARNING: This action will delete both local reference and remote instance.
> Error removing host "openshift": Host does not exist: "openshift"
> Can't remove "openshift"
> Setting up new OpenShift docker machine...
> dial tcp: missing address
> Problem with docker machine creation that I can't resolve, please raise an issue                                                                               and add error output:

**Comment by eschabell** [comment] 2017-10-28 16:29
dial tcp is networking issues on your machine....

**Comment by eschabell** [comment] 2017-11-07 11:35
Might want to look at NAT settings between your host and the Virtualbox machine(s).

**Comment by Cricen** [comment] 2017-11-21 19:50
No dude that's an annoying answer. I could ping any host on my network without issue, In any case I dropped this more than a week ago. I don't have time to keep troubleshooting it and I don't get why a redhat product demo/evaluation wouldn't work on CentOS. this could used improved document & testing especially since you guys want to charge ~2k per node for OpenShift. (just my two cents) What got me past this was starting and configuring the `libvirt` service but still it's having issues with creating a docker-machine. It got to a point where a the docker-machine tried to start but was in a failed state. 

here's more the dial tcp stuff: 
https://github.com/dhiltgen/docker-machine-kvm/issues/14

**Comment by eschabell** [comment] 2017-11-22 10:09
Since it's not an issue for you anymore and I can't reproduce.... closing this issue.

**Closed as completed by eschabell** 2017-11-22 10:09 UTC
