### ISSUE TITLE
"oc" command availability check succeeds, but oc not found in path

### ISSUE THREAD

**Issue by sot015** [redhatdemocentral/ocp-install-demo#1] opened 2016-11-16 20:39 UTC
Installing OSE with cluster up...

./init.sh: line 57: oc: command not found

Error occurred during oc cluster up command!

Cleaning out existing openshift docker machine.

**Comment by eschabell** [comment] 2016-11-17 14:56
Duplicate of issue #2, fixing there.

**Closed as completed by eschabell** 2016-11-17 14:56 UTC
