### ISSUE TITLE
Error creating machine: Error in driver during machine creation: exit status 1

### ISSUE THREAD

**Issue by sidd-harth** [redhatdemocentral/ocp-install-demo#48] opened 2018-02-08 04:41 UTC
Hi, I am trying to install OCP on win10. I downloaded the zip & ran 'init-win10.bat' with Administrative privileges. This is the error trace, kindly help me out.

OpenShift command line tools installed... checking for valid version...
Docker-machine command line tools installed...
Version of installed OpenShift command line tools correct... v3.7.9
Setting up OpenShift docker machine...
Docker machine "openshift" already exists
Error occurred during openshift docker machine creation...
Cleaning out existing 'openshift' machine...

About to remove openshift
WARNING: This action will delete both local reference and remote instance.
Successfully removed openshift
Setting up new OpenShift docker machine...
Running pre-create checks...
Creating machine...
(openshift) Downloading C:\Users\User\.docker\machine\cache\boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v1.13.1/boot2docker.iso...
(openshift) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(openshift) Creating SSH key...
(openshift) Creating VM...
(openshift) Using switch "ocpNET"
(openshift) Creating VHD
(openshift) Starting VM...
Error creating machine: Error in driver during machine creation: exit status 1

Problem with docker machine creation that I can't resolve.

**Comment by eschabell** [comment] 2018-02-08 11:32
@sidd-harth, 

This install requires Hyper-V on win10, is that installed to host the OCP installation? (I can't check for that).

**Comment by sidd-harth** [comment] 2018-02-08 11:43
@eschabell , yes Hyper-V is installed & in HyperV Manager I configured ocpNET switch...in above trace you can see OCP installation it is using it..

(openshift) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(openshift) Creating SSH key...
(openshift) Creating VM...
**(openshift) Using switch "ocpNET"**
(openshift) Creating VHD
(openshift) Starting VM...

**Comment by eschabell** [comment] 2018-02-08 15:58
Going to see if we can pull in @betazep to help with your issues, he was the one to submit the Hyper-V solution and might be able to help?

**Comment by betazep** [comment] 2018-02-09 04:23
@sidd-harth 

 How much memory do you have in your machine? Also which memory value is not commented out in the batch file? I have seen this happen when there is not enough memory to start the machine.

**Comment by betazep** [comment] 2018-02-09 04:25
I find it is a good idea to manually delete the open shift VM created in hyper V before running the script. I did have some intermittent failures when I left the script delete the VM and then re-create it.

**Comment by sidd-harth** [comment] 2018-02-09 04:43
Hi @betazep , let me explain my infrastructure a bit. I have a Win 10 Home edition(no HyperV) with 16GB memory. So I downloaded a Win 10 Enterprise OVA and running it in VirtualBox with 5GB memory. I can increase it to 8GB maybe.

Yes, I tried deleted the openshift VM manually in Hyper-V and when I run the script I get the same error.

**Comment by eschabell** [comment] 2018-02-09 07:59
@sidd-harth, I think what you might need to increase is the init-win10.bat memory settings (that's what @betazep is referring to), found on lines 22-24:

REM uncomment amount memory needed, sets RAM usage limit for OCP, default 6 GB.
REM set VM_MEMORY=10240
set VM_MEMORY=6144 
REM set VM_MEMORY=3072   

Remove the REM for the memory that you might need. This setting was defaulted to what most UNIX based systems need.

**Comment by betazep** [comment] 2018-02-09 08:54
Yeah the problem is there isn’t enough FREE memory to start the VM with docker-machine. Running OCP with three gigs is just not enough either. The hyperV VM for docker Takes two gigs of memory by itself, but I found that you can manually set that to one gig with no issue. (Inside hyperv manager)

**Comment by betazep** [comment] 2018-02-09 08:58
If you give your win 10 enterprise VM 8g, manually decrease the docker VM to 1g, and check  commit charge and see greater than 6g free... it should start the vm for you. I think it’s a hyper V problem because hyper V want to start the VM without enough physical memory to do so.

**Comment by betazep** [comment] 2018-02-09 09:00
*won’t start the VM*

**Comment by eschabell** [comment] 2018-03-20 10:15
Closing, reopen if @betazep's fix did not work for you.

**Closed as completed by eschabell** 2018-03-20 10:15 UTC
